"""empty message

Revision ID: 28317931f388
Revises: aef46ea30776
Create Date: 2016-06-07 17:39:59.808324

"""

# revision identifiers, used by Alembic.
revision = '28317931f388'
down_revision = 'aef46ea30776'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('level', mysql.TINYINT(display_width=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'level')
    ### end Alembic commands ###
