"""empty message

Revision ID: 48d269ee35fd
Revises: 4d6c87eb4fbf
Create Date: 2016-05-30 15:08:50.080072

"""

# revision identifiers, used by Alembic.
revision = '48d269ee35fd'
down_revision = '4d6c87eb4fbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('suffix', sa.String(length=256), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('languages', 'suffix')
    ### end Alembic commands ###
