"""empty message

Revision ID: 54019c745395
Revises: 28317931f388
Create Date: 2016-06-08 14:48:10.888029

"""

# revision identifiers, used by Alembic.
revision = '54019c745395'
down_revision = '28317931f388'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminuser',
    sa.Column('id', mysql.INTEGER(unsigned=True), ),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('role', mysql.TINYINT(display_width=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adminuser')
    ### end Alembic commands ###
