"""empty message

Revision ID: 6f66d9b450fa
Revises: None
Create Date: 2016-05-19 12:00:27.056014

"""

# revision identifiers, used by Alembic.
revision = '6f66d9b450fa'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cobra_task_info', sa.Column('filename', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cobra_task_info', 'filename')
    ### end Alembic commands ###
