"""empty message

Revision ID: 700efd2e57b0
Revises: f56668fdc0ba
Create Date: 2016-05-26 16:25:31.351069

"""

# revision identifiers, used by Alembic.
revision = '700efd2e57b0'
down_revision = 'f56668fdc0ba'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vul_id', mysql.TINYINT(), nullable=True),
    sa.Column('language', mysql.TINYINT(), nullable=True),
    sa.Column('regex', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    ### end Alembic commands ###
