"""empty message

Revision ID: 720e9049b572
Revises: ddd73f6b2dc7
Create Date: 2016-06-08 16:03:45.063502

"""

# revision identifiers, used by Alembic.
revision = '720e9049b572'
down_revision = 'ddd73f6b2dc7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'adminuser', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'adminuser', type_='unique')
    ### end Alembic commands ###
