"""empty message

Revision ID: 9ad18f01fdc1
Revises: 48d269ee35fd
Create Date: 2016-05-30 15:20:46.216014

"""

# revision identifiers, used by Alembic.
revision = '9ad18f01fdc1'
down_revision = '48d269ee35fd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('repo_type', mysql.TINYINT(display_width=2), nullable=False),
    sa.Column('repository', sa.String(length=256), nullable=True),
    sa.Column('branch', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('scan_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cobra_project')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cobra_project',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('repo_type', mysql.TINYINT(display_width=2), autoincrement=False, nullable=False),
    sa.Column('repository', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('branch', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('scan_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('projects')
    ### end Alembic commands ###
