"""empty message

Revision ID: 9ffa798c4399
Revises: 9ad18f01fdc1
Create Date: 2016-05-30 16:18:16.120354

"""

# revision identifiers, used by Alembic.
revision = '9ffa798c4399'
down_revision = '9ad18f01fdc1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whitelist',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(length=512), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whitelist')
    ### end Alembic commands ###
