"""empty message

Revision ID: d1e5403569bc
Revises: d9ce546dbcac
Create Date: 2016-06-03 15:01:38.771083

"""

# revision identifiers, used by Alembic.
revision = 'd1e5403569bc'
down_revision = 'd9ce546dbcac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('regex_confirm', sa.String(length=512), nullable=True))
    op.add_column('rules', sa.Column('repair', sa.String(length=512), nullable=True))
    op.add_column('rules', sa.Column('status', mysql.TINYINT(display_width=2), nullable=True))
    op.add_column('tasks', sa.Column('file_count', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('target', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('time_consume', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('time_end', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('time_start', sa.DateTime(), nullable=True))
    op.alter_column('tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('tasks', 'scan_way',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    op.alter_column('tasks', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('tasks', 'url')
    op.drop_column('tasks', 'task_type')
    op.drop_column('tasks', 'filename')
    op.add_column('vuls', sa.Column('repair', sa.String(length=512), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vuls', 'repair')
    op.add_column('tasks', sa.Column('filename', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('tasks', sa.Column('task_type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('url', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('tasks', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('tasks', 'scan_way',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    op.alter_column('tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('tasks', 'time_start')
    op.drop_column('tasks', 'time_end')
    op.drop_column('tasks', 'time_consume')
    op.drop_column('tasks', 'target')
    op.drop_column('tasks', 'file_count')
    op.drop_column('rules', 'status')
    op.drop_column('rules', 'repair')
    op.drop_column('rules', 'regex_confirm')
    ### end Alembic commands ###
