"""empty message

Revision ID: d25d42af017c
Revises: 54019c745395
Create Date: 2016-06-08 15:21:18.535523

"""

# revision identifiers, used by Alembic.
revision = 'd25d42af017c'
down_revision = '54019c745395'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adminuser', sa.Column('last_login_ip', sa.DateTime(), nullable=True))
    op.add_column('adminuser', sa.Column('last_login_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adminuser', 'last_login_time')
    op.drop_column('adminuser', 'last_login_ip')
    ### end Alembic commands ###
