"""empty message

Revision ID: ddd73f6b2dc7
Revises: d25d42af017c
Create Date: 2016-06-08 15:48:15.495171

"""

# revision identifiers, used by Alembic.
revision = 'ddd73f6b2dc7'
down_revision = 'd25d42af017c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adminuser', 'last_login_ip',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=16),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adminuser', 'last_login_ip',
               existing_type=sa.String(length=16),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    ### end Alembic commands ###
