"""empty message

Revision ID: de0dc4a55970
Revises: 89c4f4dde1a1
Create Date: 2016-05-27 16:19:32.109274

"""

# revision identifiers, used by Alembic.
revision = 'de0dc4a55970'
down_revision = '89c4f4dde1a1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('languages')
    ### end Alembic commands ###
