"""empty message

Revision ID: e8340005de4c
Revises: 6f66d9b450fa
Create Date: 2016-05-19 13:45:10.849359

"""

# revision identifiers, used by Alembic.
revision = 'e8340005de4c'
down_revision = '6f66d9b450fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cobra_task_info', sa.Column('level', sa.SmallInteger(), nullable=False))
    op.add_column('cobra_task_info', sa.Column('new_version', sa.String(length=40), nullable=True))
    op.add_column('cobra_task_info', sa.Column('old_version', sa.String(length=40), nullable=True))
    op.add_column('cobra_task_info', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('cobra_task_info', sa.Column('scan_type', sa.SmallInteger(), nullable=False))
    op.add_column('cobra_task_info', sa.Column('scan_way', sa.SmallInteger(), nullable=False))
    op.add_column('cobra_task_info', sa.Column('url', sa.String(length=255), nullable=True))
    op.add_column('cobra_task_info', sa.Column('username', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cobra_task_info', 'username')
    op.drop_column('cobra_task_info', 'url')
    op.drop_column('cobra_task_info', 'scan_way')
    op.drop_column('cobra_task_info', 'scan_type')
    op.drop_column('cobra_task_info', 'password')
    op.drop_column('cobra_task_info', 'old_version')
    op.drop_column('cobra_task_info', 'new_version')
    op.drop_column('cobra_task_info', 'level')
    ### end Alembic commands ###
