"""empty message

Revision ID: f56668fdc0ba
Revises: e8340005de4c
Create Date: 2016-05-26 12:34:27.333049

"""

# revision identifiers, used by Alembic.
revision = 'f56668fdc0ba'
down_revision = 'e8340005de4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cobra_task_info', sa.Column('branch', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cobra_task_info', 'branch')
    ### end Alembic commands ###
