"""empty message

Revision ID: f5d5ac64ccfa
Revises: 5f35f8c0359c
Create Date: 2016-06-07 11:45:59.550663

"""

# revision identifiers, used by Alembic.
revision = 'f5d5ac64ccfa'
down_revision = '5f35f8c0359c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('task_id', mysql.INTEGER(display_width=11), nullable=True))
    op.drop_column('results', 'scan_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('scan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('results', 'task_id')
    ### end Alembic commands ###
